threshold_x = 300;
threshold_y = 64;
obstacle_max = 16;
movespeed = 1;
movespeed_chase = 3;
normal_grav = 0.5;
grav = normal_grav;
walkspr = spr_monstercheese_walk;
idlespr = spr_monstercheese_idle;
fallspr = spr_monstercheese_idle;
chasespr = spr_monstercheese_chase;
changeside_buffer = 0;
hsp = 0;
vsp = 0;
state = states.normal;
grounded = 0;
event_inherited();
monsterid = 1;
